name = "vascular_trees"
uuid = "87ddc3cc-728b-4545-b71e-e2b9cf7abe66"
authors = ["Mariia Myshkina", "Matthias König"]
version = "0.1.0"

[deps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
OrdinaryDiffEq = "6.90.1"
Plots = "1.40.9"
julia = ">=1.5"
