"""
Convert graphs generated by SyntheticVascularTrees.jl into .arrow tables used by the simulations.

Run: `julia --project src/build_arrow_graphs.jl` (processing starts as soon as the file is included).

What must be specified below:
1. t_options (tree configurations and numbers of nodes)

Supported configurations: those in `tree_definitions` (src/common/definitions.jl),
currently "Rectangle_quad" and "Rectangle_trio".

Inputs (per vascular tree, e.g. A, P, V, B), expected in
`results/julia_vessel_trees/<tree_configuration>/<tree_configuration>_<n_nodes>/julia/`:
1. `<tree>.lg`        - edge list (graph skeleton)
2. `<tree>_edges.csv` - edge attributes
3. `<tree>_nodes.csv` - node attributes

Outputs, in the `graphs/` folder of the graph directory:
1. `<tree>.arrow` - one table per vascular tree (ODE groups, ids, flows, volumes, ...)
2. `T.arrow`      - terminal nodes, i.e. the connection points between the trees
"""

module ProcessJuliaGraph
    """
    TODO: Optimize code
    """
    # === Imports ===
    using Revise
    using VascularTrees
    using VascularTrees.Process_Individual_Trees: process_julia_graph
    using VascularTrees.Process_Terminal_Nodes: process_terminal_nodes

    # Definitions of the available tree configurations (inflow / outflow trees)
    const trees::tree_definitions = tree_definitions()


    # ============================ Options ============================

    # === Graph options ===
    # options for graph, i.e., number of nodes and type of tree
    t_options = tree_options(
        n_nodes = [100],  #1000, 10000, 100000, 100000
        tree_configurations = [
            "Rectangle_quad",
        ],
    )


    # ============================== Run ==============================

    function process_all_trees()
        for tree_configuration ∈ t_options.tree_configurations
            for n_node ∈ t_options.n_nodes
                # fill the tree structure with the info for this tree
                tree_info =
                    Tree_structure(; tree_configuration = tree_configuration, n_node = n_node, tree_components = trees.vascular_trees[tree_configuration])
                @info "Working on $(tree_info.graph_id)"
                # load (.lg and .csv), process and save (as .arrow) each graph (vascular tree) that this 
                # tree includes structure individually
                process_julia_graph(tree_info)
                # load (.arrow) every graph that this tree includes similtaneously, collect info that we
                # need for the correct ODEs for the terminal part that connects all the parts of this tree
                # together and save it in one file (as .arrow)
                process_terminal_nodes(tree_info)
            end
        end
    end

    process_all_trees()

end
